name: LAMP Deployment

on: 
   workflow_dispatch:
  
jobs:
  Linting:
    name: Linting ansible files
    runs-on: ubuntu-latest
    steps:
      - name: checkout the source 
        uses: actions/checkout@v3
      - name: Ansible Linting
        uses: ansible-community/ansible-lint-action@v6.3.0
        with:
          path: "ansible/"
          args: "ansible/.ansible-lint"
       
