name: LAMP Deployment

on: 
  repository_dispatch:
  
jobs:
  Linting:
    name: Linting ansible files
    runs-on: ubuntu-latest
    steps:
      - name: checkout the source 
        uses: actions/checkout@v3
      - name: Ansible Linting
        uses: ansible-community/ansible-lint-action@v6.3.0
        with:
          targets: |
            ansible/playbook.yml
            ansible/inventory.yml
       
