name: LAMP Deployment

on: 
   workflow_dispatch:
  
jobs:
  Linting:
    name: Linting ansible files
    runs-on: ubuntu-latest
    steps:
      - name: checkout the source 
        uses: actions/checkout@v3
#       - name: Ansible Linting
#         uses: ansible/ansible-lint-action@c37fb7b4bda2c8cb18f4942716bae9f11b0dc9bc
#         with:
#          targets: |
#           ansible/playbook.yml
#           ansible/inventory.yml
#          args: "-c ansible/.ansible-lint
      - name: publish playbook artifact
        uses: actions/upload-artifact@v2
        with:
         name: playbooks
         path: ansible 
 
  deploy:
      name: Deploy to server 
      runs-on: ubuntu-latest
      steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: playbooks
          path: ansible

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ansible
          options: |
            --inventory inventory.yml

      
   
